# Generated by Django 4.2.6 on 2023-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_postdetailtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
