# Generated by Django 4.2.6 on 2024-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('館藏中', '館藏中'), ('預約中', '預約中'), ('借出中', '借出中')], max_length=8)),
                ('Author', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
