# Generated by Django 4.2.6 on 2024-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_search_delete_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search',
            new_name='Book',
        ),
    ]
