# Generated by Django 4.2.4 on 2024-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_search_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
